{
 "title": "Backend Engineering Lab - Chaos Dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "API Request Latency (P95 vs Max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, uri) (rate(http_server_requests_seconds_bucket{uri=~\"/api/users.*\"}[1m]))) * 1000",
     "legendFormat": "{{uri}} P95 Latency (ms)"
    },
    {
     "expr": "max by (uri) (max_over_time(http_server_requests_seconds_max{uri=~\"/api/users.*\"}[1m])) * 1000",
     "legendFormat": "{{uri}} Max Latency (ms)"
    }
   ]
  },
  {
   "title": "Total API Requests (by HTTP Status)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_count{uri=~\"/api/users.*\"}[1m]))",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Active Faults Injected (by Scenario)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(fault_injected_total_total[1m])) by (scenario)",
     "legendFormat": "{{scenario}}"
    }
   ]
  }
 ]
}