spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:backendlab}
    username: ${POSTGRES_USER:labuser}
    password: ${POSTGRES_PASSWORD:labpassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

app:
  order-service:
    url: ${ORDER_SERVICE_URL:http://localhost:8081/api/orders}

logging:
  level:
    com.backendlab: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    org.hibernate.SQL: WARN
